openapi: 3.0.3
info:
  title: P-7 WebService
  description: 'WebService to distribute computations'
  license:
    name: Don't know
    url: 
  version: 1.0.0
servers:
- url: can't remember
tags:
- name: batch
  description: A batch containing an executable able to perform the
               desired computations, and a set of inputs that should be computed
- name: task
  description: A task that is ready to be computed

paths:
  /batch:
    post:
      tags:
      - batch
      summary: Add a batch to be computed
      operationId: AddBatch
      requestBody:
        description: Batch object that should be computed
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Batch'
        required: true
      responses:
        202:
          description: Batch has been added to queue
          content: {}
        400:
          description: Invalid input
          content: {}
        401:
          description: Not logged in
          content: {}
      x-codegen-request-body-name: body

  /task/ready:
    get:
      tags:
      - task
      summary: Returns a task that is ready to be computed
      operationId: GetReadyTask
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /api/HeartBeat:
    get:
      tags:
      - HeartBeat
      summary: Status message of devices
      operationId: HeartBeat
      responses:
        200:
          description: HeartBeat successfully received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeartBeat'
        400:
          description: Incorrect heartbeat type.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeartBeat'

  /task/complete:
    post:
      tags:
      - task
      summary: Receives a file containing the result of the Task with ID
      operationId: AddResult
      requestBody:
        description: Information about completed Task
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompletedTask'
      responses:
        201:
          description: Successful creation
        400:
          description: Invalid input
        401:
          description: Not logged in

